# Generated by Django 6.0.1 on 2026-02-04 02:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoptions', '0001_initial'),
        ('cats', '0021_cat_tagline'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cats.cat'),
        ),
    ]
