# Generated by Django 6.0.1 on 2026-02-04 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoptions', '0002_application_cat'),
        ('cats', '0021_cat_tagline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='cat',
        ),
        migrations.AddField(
            model_name='application',
            name='cat',
            field=models.ManyToManyField(null=True, to='cats.cat'),
        ),
    ]
