# Generated by Django 6.0.1 on 2026-02-04 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoptions', '0003_remove_application_cat_application_cat'),
        ('cats', '0021_cat_tagline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='cat',
            field=models.ManyToManyField(related_name='applications', to='cats.cat'),
        ),
    ]
