# Generated by Django 6.0.1 on 2026-02-04 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adoptions', '0004_alter_application_cat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='cat',
            new_name='cats',
        ),
    ]
