# Generated by Django 6.0.1 on 2026-02-04 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoptions', '0005_rename_cat_application_cats'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='occupation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='application',
            name='email',
            field=models.EmailField(max_length=50),
        ),
    ]
