# Generated by Django 6.0.1 on 2026-02-04 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoptions', '0006_application_occupation_alter_application_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='accommodation_type',
            field=models.CharField(blank=True, choices=[('home_owner', 'Home ownder'), ('renting', 'Renting on your own or with a partner'), ('house_share', 'House sharing'), ('other', 'Other')], max_length=50),
        ),
        migrations.AddField(
            model_name='application',
            name='allergies',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='busy_street',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='children_and_ages',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='application',
            name='home_additional_info',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='application',
            name='home_photos',
            field=models.FileField(blank=True, upload_to='applications/home_photos/'),
        ),
        migrations.AddField(
            model_name='application',
            name='hours_alone',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='application',
            name='how_found_cat',
            field=models.CharField(blank=True, choices=[('9liveswebsite', '9 Lives website'), ('9livesfoster', '9 Lives foster carer'), ('facebook', 'Facebook'), ('gumtree', 'Gumtree'), ('instagram', 'Instagram'), ('friendfamily', 'Friend or family member'), ('other', 'Other')], max_length=50),
        ),
        migrations.AddField(
            model_name='application',
            name='number_of_people',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='application',
            name='reason_for_adopting',
            field=models.TextField(blank=True),
        ),
    ]
