# Generated by Django 6.0.1 on 2026-02-04 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoptions', '0007_application_accommodation_type_application_allergies_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='other_pets',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='other_pet_types',
            field=models.ManyToManyField(blank=True, to='adoptions.pettype'),
        ),
    ]
