# Generated by Django 6.0.1 on 2026-02-04 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoptions', '0008_pettype_application_other_pets_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='other_pet_types',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='other_pets',
            new_name='other_pets_cat',
        ),
        migrations.AddField(
            model_name='application',
            name='other_pets_dog',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='other_pets_microchipped',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='other_pets_other',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='other_pets_rabbit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='other_pets_sterilised',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='other_pets_vaccinated',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='PetType',
        ),
    ]
