# Generated by Django 6.0.1 on 2026-02-04 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoptions', '0009_remove_application_other_pet_types_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='adoption_refusal_history',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='application',
            name='can_afford_care',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='diet_plan',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='application',
            name='indoor_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='lost_cat_plan',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='application',
            name='medical_care_plan',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='application',
            name='other_pet_additional_info',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='application',
            name='other_pet_behaviour',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='application',
            name='previous_cat_experience',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='application',
            name='surrendered_animals_history',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='application',
            name='will_return_if_needed',
            field=models.BooleanField(default=False),
        ),
    ]
