# Generated by Django 6.0.1 on 2026-02-06 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoptions', '0010_application_adoption_refusal_history_and_more'),
        ('cats', '0021_cat_tagline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='accommodation_type',
            field=models.CharField(blank=True, choices=[('home_owner', 'Home owner'), ('renting', 'Renting on your own or with a partner'), ('house_share', 'House sharing'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='application',
            name='cats',
            field=models.ManyToManyField(blank=True, related_name='applications', to='cats.cat'),
        ),
    ]
