# Generated by Django 6.0.1 on 2026-02-11 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoptions', '0011_alter_application_accommodation_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='driving_license',
            field=models.FileField(blank=True, upload_to='applications/driving_licenses/'),
        ),
        migrations.AddField(
            model_name='application',
            name='vet_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
