# Generated by Django 6.0.1 on 2026-02-09 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='logo',
            field=models.FileField(blank=True, upload_to='vets/logos/'),
        ),
    ]
