# Generated by Django 6.0.1 on 2026-02-09 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vets', '0002_application_logo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Application',
            new_name='Vet',
        ),
    ]
