# Generated by Django 6.0.1 on 2026-02-09 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vets', '0003_rename_application_vet'),
    ]

    operations = [
        migrations.AddField(
            model_name='vet',
            name='website',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
