# Generated by Django 6.0.1 on 2026-02-09 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vets', '0004_vet_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='vet',
            name='phone',
            field=models.CharField(default='08', max_length=50),
            preserve_default=False,
        ),
    ]
