# Generated by Django 6.0.1 on 2026-01-14 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FosterHome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending Approval')], default='pending', max_length=20)),
                ('address_line1', models.CharField(max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('prefers_kittens', models.BooleanField(default=False)),
                ('prefers_adults', models.BooleanField(default=False)),
                ('prefers_seniors', models.BooleanField(default=False)),
                ('prefers_medical_cases', models.BooleanField(default=False)),
                ('prefers_short_term', models.BooleanField(default=False)),
                ('prefers_long_term', models.BooleanField(default=False)),
                ('max_cats', models.PositiveIntegerField(default=1)),
                ('has_other_cats', models.BooleanField(default=False)),
                ('has_dogs', models.BooleanField(default=False)),
                ('has_children', models.BooleanField(default=False)),
                ('outdoor_space', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
