# Generated by Django 6.0.1 on 2026-01-14 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fosterhomes', '0002_fosterhome_created_by_fosterhome_current_cats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fosterhome',
            name='current_cats',
        ),
    ]
