# Generated by Django 6.0.1 on 2026-01-14 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cat',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='cat',
            name='slug',
        ),
        migrations.AddField(
            model_name='cat',
            name='sex',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('unknown', 'Unknown')], default='unknown', max_length=20),
        ),
    ]
