# Generated by Django 6.0.1 on 2026-01-14 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0002_remove_cat_gender_remove_cat_slug_cat_sex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cat',
            name='age',
        ),
        migrations.AddField(
            model_name='cat',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
