# Generated by Django 6.0.1 on 2026-01-14 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0003_remove_cat_age_cat_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='colour',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
