# Generated by Django 6.0.1 on 2026-01-14 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0004_cat_colour'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='is_desexed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cat',
            name='is_fiv_positive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cat',
            name='is_good_with_cats',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cat',
            name='is_good_with_dogs',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cat',
            name='is_good_with_kids',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cat',
            name='is_microchipped',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cat',
            name='is_vaccinated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cat',
            name='microchip_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
