# Generated by Django 6.0.1 on 2026-01-14 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0005_cat_is_desexed_cat_is_fiv_positive_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='estimated_dob',
            field=models.BooleanField(default=False),
        ),
    ]
