# Generated by Django 6.0.1 on 2026-01-14 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0006_cat_estimated_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='bonded_cats',
            field=models.ManyToManyField(blank=True, to='cats.cat'),
        ),
    ]
