# Generated by Django 6.0.1 on 2026-01-14 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0007_cat_bonded_cats'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cats/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cats.cat')),
            ],
        ),
    ]
