# Generated by Django 6.0.1 on 2026-01-14 06:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0008_catimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='catimage',
            name='primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='catimage',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
