# Generated by Django 6.0.1 on 2026-01-14 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0010_catbreed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cat',
            name='photo',
        ),
    ]
