# Generated by Django 6.0.1 on 2026-01-14 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0011_remove_cat_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='cats/'),
        ),
    ]
