# Generated by Django 6.0.1 on 2026-01-14 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0012_cat_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cat',
            old_name='breed',
            new_name='breed_string',
        ),
    ]
