# Generated by Django 6.0.1 on 2026-01-14 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0013_rename_breed_cat_breed_string'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='breed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cats.catbreed'),
        ),
    ]
