# Generated by Django 6.0.1 on 2026-01-14 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0014_cat_breed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cat',
            name='breed_string',
        ),
    ]
