# Generated by Django 6.0.1 on 2026-01-14 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0015_remove_cat_breed_string'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cat',
            name='photo',
        ),
    ]
