# Generated by Django 6.0.1 on 2026-01-15 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0016_remove_cat_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cat',
            old_name='is_desexed',
            new_name='is_sterilised',
        ),
        migrations.AddField(
            model_name='cat',
            name='good_with_cats_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cat',
            name='good_with_dogs_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cat',
            name='good_with_kids_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cat',
            name='health_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cat',
            name='vaccinated_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='cat',
            name='is_good_with_cats',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cat',
            name='is_good_with_dogs',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cat',
            name='is_good_with_kids',
            field=models.BooleanField(default=False),
        ),
    ]
