# Generated by Django 6.0.1 on 2026-01-15 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0017_rename_is_desexed_cat_is_sterilised_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='fostered_in',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
