# Generated by Django 6.0.1 on 2026-01-15 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0018_cat_fostered_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='fostered_in',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
