# Generated by Django 6.0.1 on 2026-01-15 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0019_alter_cat_fostered_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='good_with_cats_notes',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='cat',
            name='good_with_dogs_notes',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='cat',
            name='good_with_kids_notes',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='cat',
            name='health_notes',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='cat',
            name='vaccinated_notes',
            field=models.CharField(blank=True),
        ),
    ]
