# Generated by Django 6.0.1 on 2026-01-19 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0020_alter_cat_good_with_cats_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='tagline',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
