# Generated by Django 6.0.1 on 2026-02-10 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0021_cat_tagline'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catimage',
            options={'ordering': ['order', '-uploaded_at']},
        ),
        migrations.AddField(
            model_name='catimage',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
