# Generated by Django 6.0.1 on 2026-02-10 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0022_alter_catimage_options_catimage_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='is_special_needs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cat',
            name='special_needs_notes',
            field=models.CharField(blank=True),
        ),
    ]
